# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
tagline:          'Podcast'
baseurl:          /
paginate:         500
collections:
  episodes:
    output:       true

# Podcast parameters
podcast_title:    PardonMySurf – Le Podcast
podcast_description:  Bienvenue dans PardonMySurf, le podcast pour les surfeurs passionnés et ceux qui veulent le devenir. 

# Default parameters
defaults:
  -
    scope:
      path: ""
      type: "episodes"
    values:
      layout: episode
      image: https://pardonmysurf.github.io/public/img/pms_logo.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

#SEO tag
title:            PardonMySurf
description:      Podcast
url:              https://pardonmysurf.github.io/

author:
  name:           'PardonMySurf'
  instagram:      https://www.instagram.com/pardonmysurf/
social:
  name:           PardonMySurf
  links:
                  - https://www.instagram.com/pardonmysurf/
lang:             fr

plugins:
                  - jekyll-seo-tag
