name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest .

  jekyll-build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll:3.8
    steps:
      - name: Prepare repo
        uses: actions/checkout@v3

      - name: Make directory
        run: mkdir -vp /__w/pardonmysurf.github.io/pardonmysurf.github.io/_site

      - name: Build Jekyll site
        run: jekyll build --config _config.yml,_config-lhci.yml

      - name: Upload built site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: /__w/pardonmysurf.github.io/pardonmysurf.github.io/_site

  htmlproofer-test:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v3
        with:
          path: /home/runner/work/pardonmysurf.github.io/pardonmysurf.github.io

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "/home/runner/work/pardonmysurf.github.io/pardonmysurf.github.io"
          arguments: --external_only --url_ignore "https://www.cairn.info/commun--9782707186737.htm,https://www.cerveauetpsycho.fr/sd/psychotherapie/il-faut-autoriser-les-therapies-psychedeliques-18929.php,https://www.fun-mooc.fr/fr/cours/fabriquer-linnovation/"

  lighthouse-test:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@v3

      - name: Keep only Lighthouse config file
        run: find . \! -name '.lighthouserc.js' -delete

      - name: Download built site
        uses: actions/download-artifact@v3
        with:
          path: /home/runner/work/pardonmysurf.github.io/pardonmysurf.github.io

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create a folder for LHCI lhci_results
        run: mkdir -vp /home/runner/work/lhci_results

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci collect --config /home/runner/work/pardonmysurf.github.io/pardonmysurf.github.io/.lighthouserc.js
          lhci upload --config /home/runner/work/pardonmysurf.github.io/pardonmysurf.github.io/.lighthouserc.js

      - name: Upload LHCI results
        uses: actions/upload-artifact@v3
        with:
          name: lhci_results
          path: /home/runner/work/lhci_results

      - name: Assert Lighthouse CI
        run: lhci assert --config /home/runner/work/pardonmysurf.github.io/pardonmysurf.github.io/.lighthouserc.js
